export const links = {
  main: '/',
  home: '/app/home',
  profile: '/app/profile/account',
  profileTheme: '/app/profile/theme',
  email: '/app/profile/account/email',
  password: '/app/profile/account/password',
  history: '/app/history',
  expenses: '/app/expenses',
  income: '/app/income',
  login: '/auth/login',
  signup: '/auth/signup',
  addExpense: '/app/add-expense',
  addRevenue: '/app/add-revenue',
  contacts: '/app/contacts',
}
